services:
  app:
    build: .
    container_name: project_service_app
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/projects_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - .:/app
    networks:
      - config

  db:
    image: postgres:14
    container_name: project_service_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projects_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata_project:/var/lib/postgresql/data
    networks:
      - config
  grpc_server:
    build: .
    command: ["python", "app/presentation/grpc/run_grpc.py"]
    container_name: grpc_server
    depends_on:
      - db
    ports:
      - "50051:50051"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/projects_db
    networks:
      - config


volumes:
  pgdata_project:

networks:
  config:
    external: true
